#pragma once
#include <string>
#include "./Target/d3dUtility.h"
#include "./Target/Common.h"
#include "./Target/ShmFile.h"
#include "./Target/camera.h"
#include "./Target/CRenderObject.h"
#include "./Target/DirectInputClass.h"
#include "./Target/CBoard.h"
#include "./Target/CRenderObjectCube.h"
#include "./Target/CRenderCubeTexture.h"
#include "./Target/CRenderTexture.h"
#include "./Target/CShadowVolumeMesh.h"
#include "./Target/CParticle.h"